version: "3.10"

services:
  lmss_entity_recognizer:
    build: .
    ports:
      - "8000:8000"
      - "8001:8001"
    volumes:
      - .:/app
      - lmss_data:/app/app/lmss
      - lmss_cache:/app/cache
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/lmss/status"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: >
      /bin/sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 & uvicorn app.local_api:app --host 0.0.0.0 --port 8001"

volumes:
  lmss_data:
  lmss_cache: